Repository svelteuidev/svelteui, pull requests merged in 2022-11, with the labels that each got.

#220 [docs]: Documentation for Chip and ChipGroup
  apps/docs/src/includes/sidebar.md
  apps/docs/src/pages/core/chip.md
  apps/docs/svelte-docs.config.js
  packages/svelteui-core/package.json
  packages/svelteui-core/src/components/Chip/Chip.stories.svelte
  packages/svelteui-core/src/components/Chip/Chip.svelte
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.styles.ts
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.svelte
  packages/svelteui-core/src/components/Menu/Menu.stories.svelte
  packages/svelteui-core/src/components/Switch/Switch.svelte
  packages/svelteui-core/src/components/index.ts
  packages/svelteui-demos/src/demos/core/Chip/Chip.demo.configurator.svelte
  packages/svelteui-demos/src/demos/core/Chip/Chip.demo.states.svelte
  packages/svelteui-demos/src/demos/core/Chip/ChipGroup.demo.configurator.svelte
  packages/svelteui-demos/src/demos/core/Chip/index.ts
  packages/svelteui-demos/src/index.ts
Labels: documentation

#228 [@svelteuidev/demos] Fixes #225: Gradient problem in docs
  apps/docs/package.json
  packages/svelteui-core/src/components/Badge/Badge.stories.svelte
  packages/svelteui-core/src/components/Chip/Chip.stories.svelte
  packages/svelteui-demos/src/components/Configurator/controls/CompositeControl.svelte
  packages/svelteui-demos/src/components/Configurator/controls/ControlsRenderer.svelte
  packages/svelteui-prism/src/dist/Prism/Prism.styles.ts
  yarn.lock
Labels: bug

#229 [docs]: Tweaks, capitalization and fixing typos
  apps/docs/src/pages/basics.md
  apps/docs/src/pages/composables/use-click-outside.md
  apps/docs/src/pages/composables/use-clipboard.md
  apps/docs/src/pages/composables/use-css-variable.md
  apps/docs/src/pages/composables/use-focus-within.md
  apps/docs/src/pages/composables/use-hot-key.md
  apps/docs/src/pages/composables/use-lock-scroll.md
  apps/docs/src/pages/composables/use-os.md
  apps/docs/src/pages/composables/use-portal.md
  apps/docs/src/pages/composables/use-raf-fn.md
  apps/docs/src/pages/contributing.md
  apps/docs/src/pages/core/action-icon.md
  apps/docs/src/pages/core/app-shell.md
  apps/docs/src/pages/core/badge.md
  apps/docs/src/pages/core/box.md
  apps/docs/src/pages/core/button.md
  apps/docs/src/pages/core/card.md
  apps/docs/src/pages/core/container.md
  apps/docs/src/pages/core/divider.md
  apps/docs/src/pages/core/grid.md
  apps/docs/src/pages/core/group.md
  apps/docs/src/pages/core/image.md
  apps/docs/src/pages/core/input-wrapper.md
  apps/docs/src/pages/core/input.md
  apps/docs/src/pages/core/media-query.md
  apps/docs/src/pages/core/menu.md
  apps/docs/src/pages/core/modal.md
  apps/docs/src/pages/core/native-select.md
  apps/docs/src/pages/core/notification.md
  apps/docs/src/pages/core/number-input.md
  apps/docs/src/pages/core/observer-render.md
  apps/docs/src/pages/core/overlay.md
  apps/docs/src/pages/core/popper.md
  apps/docs/src/pages/core/progress.md
  apps/docs/src/pages/core/seo.md
  apps/docs/src/pages/core/simple-grid.md
  apps/docs/src/pages/core/space.md
  apps/docs/src/pages/core/switch.md
  apps/docs/src/pages/core/tabs.md
  apps/docs/src/pages/core/text.md
  apps/docs/src/pages/core/theme-icon.md
  apps/docs/src/pages/core/tooltip.md
  apps/docs/src/pages/core/typography-provider.md
  apps/docs/src/pages/core/unstyled-button.md
  apps/docs/src/pages/dates/getting-started-dates.md
  apps/docs/src/pages/dates/month.md
  apps/docs/src/pages/faq.md
  apps/docs/src/pages/preprocessors/view-source.md
  apps/docs/src/pages/theming/create-styles.md
  apps/docs/src/pages/theming/default-theme.md
  apps/docs/src/pages/theming/override.md
  apps/docs/src/pages/theming/ssr.md
  apps/docs/src/pages/theming/svelteui-provider.md
  apps/docs/src/pages/theming/utilities.md
Labels: documentation

#223 [@svelteui/core]: Add IconRenderer to various components that support `HTMLOrSVGElement` icon prop
  packages/svelteui-core/src/components/Alert/Alert.svelte
  packages/svelteui-core/src/components/IconRenderer/IconRenderer.stories.svelte
  packages/svelteui-core/src/components/IconRenderer/IconRenderer.styles.ts
  packages/svelteui-core/src/components/IconRenderer/IconRenderer.svelte
  packages/svelteui-core/src/components/IconRenderer/IconRendererUsage.stories.svelte
  packages/svelteui-core/src/components/IconRenderer/index.ts
  packages/svelteui-core/src/components/Input/Input.svelte
  packages/svelteui-core/src/components/Menu/MenuItem/MenuItem.svelte
  packages/svelteui-core/src/components/Notification/Notification.svelte
  packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte
Labels: enhancement

#234 [docs] fix links to docs in header (missing "/apps")
  apps/docs/src/components/Heading.svelte
Labels: bug, documentation

#235 [docs] svelte global CSS for use in overrides
  apps/docs/src/pages/theming/override.md
Labels: documentation
