Repository svelteuidev/svelteui, pull requests merged in 2022-12, with the labels that each got.

#238 [svelteuidev/core] Fixes #230: make Code props optional
  packages/svelteui-core/src/components/Code/Code.styles.ts
Labels: bug

#239 [@svelteuidev/core] Fix modal target problem
  packages/svelteui-core/src/components/Affix/Affix.styles.ts
  packages/svelteui-core/src/components/Badge/Badge.stories.svelte
  packages/svelteui-core/src/components/Modal/Modal.svelte
  packages/svelteui-demos/src/demos/core/Modal/ModalForm.svelte
Labels: bug

#244 [docs]: Improvements in sentences and changed styling of NextSteps component
  apps/docs/src/pages/basics.md
  apps/docs/src/pages/composables/use-io.md
  apps/docs/src/pages/composables/use-long-press.md
  apps/docs/src/pages/contributing.md
  apps/docs/src/pages/core/app-shell.md
  apps/docs/src/pages/core/card.md
  apps/docs/src/pages/core/center.md
  apps/docs/src/pages/core/code.md
  apps/docs/src/pages/core/container.md
  apps/docs/src/pages/core/grid.md
  apps/docs/src/pages/core/group.md
  apps/docs/src/pages/core/input-wrapper.md
  apps/docs/src/pages/core/input.md
  apps/docs/src/pages/core/loader.md
  apps/docs/src/pages/core/media-query.md
  apps/docs/src/pages/core/menu.md
  apps/docs/src/pages/core/modal.md
  apps/docs/src/pages/core/overlay.md
  apps/docs/src/pages/core/popper.md
  apps/docs/src/pages/core/progress.md
  apps/docs/src/pages/core/switch.md
  apps/docs/src/pages/dates/getting-started-dates.md
  apps/docs/src/pages/dates/month.md
  apps/docs/src/pages/faq.md
  apps/docs/src/pages/installation.md
  apps/docs/src/pages/introduction.md
  apps/docs/src/pages/others/prism.md
  apps/docs/src/pages/preprocessors/getting-started-preprocessors.md
  apps/docs/src/pages/theming/create-styles.md
  apps/docs/src/pages/theming/override.md
  apps/docs/src/pages/theming/ssr.md
  apps/docs/src/pages/theming/svelteui-provider.md
  apps/docs/src/theme/ui/Sibling/Sibling.styles.js
  apps/docs/src/theme/ui/Sibling/Sibling.svelte
Labels: documentation, enhancement

#247 [@svelteui/demos] Fixed incorrect value being shown in GridDemo
  packages/svelteui-demos/src/components/Configurator/controls/SizeControl.svelte
Labels: bug

#246 [core]: #205: Exclude peer deps in syncpack set-semver-ranges script
  package.json
Labels: bug

#248 [@svelteuidev/core] Fix grid spacing
  packages/svelteui-core/src/components/Grid/Col/Col.styles.ts
  packages/svelteui-core/src/components/Grid/Col/Col.svelte
Labels: bug

#245 [@svelteuidev/core] #217: fix menu open/close events not being dispatched
  packages/svelteui-core/src/components/Menu/Menu.svelte
Labels: bug

#243 [@svelteuidev/composables] Fixes #241: focus trap action and usage on modal
  apps/docs/src/includes/sidebar.md
  apps/docs/src/pages/composables/use-focus-trap.md
  packages/svelteui-composables/src/actions/index.ts
  packages/svelteui-composables/src/actions/use-focus-trap/index.ts
  packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.stories.svelte
  packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.ts
  packages/svelteui-composables/src/actions/use-focus/use-focus.ts
  packages/svelteui-core/src/components/Modal/Modal.svelte
Labels: bug, enhancement

#252 [docs]: added missing info for NativeSelect data if data is array of objects
  apps/docs/src/pages/core/native-select.md
  packages/svelteui-core/src/components/NativeSelect/NativeSelect.stories.svelte
  packages/svelteui-core/src/components/NativeSelect/NativeSelect.svelte
  packages/svelteui-demos/src/demos/core/NativeSelect/NativeSelect.demo.objects.svelte
  packages/svelteui-demos/src/demos/core/NativeSelect/index.ts
Labels: documentation, enhancement

#261 [@svelteuidev/core] #258: Make Anchor props optional and complete docs
  apps/docs/src/pages/core/anchor.md
  packages/svelteui-core/src/components/Anchor/Anchor.styles.ts
Labels: bug, component

#266 [@svelteui/core]: Add slots for icon and label in `Tabs.Tab`
  apps/docs/src/pages/core/tabs.md
  packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte
  packages/svelteui-core/src/components/Tabs/Tabs.stories.svelte
Labels: enhancement, component

#260 [@svelteui/core] Allow CSS pointer events in Popper
  packages/svelteui-core/src/components/Popper/Popper.styles.ts
Labels: bug, component

#267 [@svelteui/core]: change ChipGroup `value` type based on `multiple` prop value
  packages/svelteui-core/src/components/Chip/Chip.svelte
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.styles.ts
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.svelte
  packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte
Labels: bug
