Repository svelteuidev/svelteui, pull requests merged in 2023-01, with the labels that each got.

#270 [@svelteui/core]: make image props optional
  packages/svelteui-core/src/components/Image/BackgroundImage/BackgroundImage.styles.ts
  packages/svelteui-core/src/components/Image/Image.styles.ts
Labels: bug, component

#269 [@svelteui/core] Generate random id for input label in TextInput component
  packages/svelteui-core/src/components/TextInput/TextInput.svelte
Labels: bug, component

#271 [@svelteui/core]: Tabs.Tab `iconProps` prop
  apps/docs/src/pages/core/tabs.md
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte
  packages/svelteui-core/src/components/Tabs/Tab/Tab.styles.ts
  packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte
Labels: enhancement, component

#264 [docs]: Added some examples of components in the homepage
  apps/docs/src/components/homepage/ComponentsExample.svelte
  apps/docs/src/components/homepage/index.js
  apps/docs/src/pages/index.md
  apps/docs/src/theme.css
  apps/docs/svelte-docs.config.js
Labels: documentation, enhancement

#257 [@svelteui/core]: fix IconRenderer for SSR
  packages/svelteui-core/src/components/IconRenderer/IconRenderer.svelte
Labels: bug, component

#276 [@svelteui/core]: Fixes #275: temporary fix for passing HTML attributes to components
  packages/svelteui-core/src/components/Button/Button.styles.ts
  packages/svelteui-core/src/components/IconRenderer/IconRenderer.svelte
  packages/svelteui-core/src/components/Input/Input.styles.ts
  packages/svelteui-core/src/components/TextInput/TextInput.styles.ts
  packages/svelteui-core/src/components/TextInput/TextInput.svelte
  packages/svelteui-core/src/styles/theme/types/DefaultProps.ts
  packages/svelteui-core/src/styles/theme/types/index.ts
Labels: bug

#279 [@svelteui/core] Fixes #277: Native select change event being called before the value is changed
  packages/svelteui-core/src/components/Input/Input.svelte
  packages/svelteui-core/src/components/NativeSelect/NativeSelect.stories.svelte
  packages/svelteui-core/src/components/TextInput/TextInput.svelte
  packages/svelteui-core/src/components/Title/Title.stories.svelte
Labels: bug

#263 [@svelteui/core]: #172: function to inject Stitches stylesheet as a hook (fixes SSR FOUC)
  apps/docs/src/pages/theming/ssr.md
  packages/svelteui-core/src/styles/index.ts
  packages/svelteui-core/src/styles/ssr.ts
  packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte
  packages/svelteui-core/src/styles/theme/SvelteUIProvider/index.ts
  packages/svelteui-core/src/styles/theme/SvelteUIProvider/svelteui.provider.ts
Labels: bug

#284 [update]: next minor
  apps/docs/src/components/TopBar/TopBar.svelte
  apps/docs/src/components/TopBar/data.js
  apps/docs/src/components/homepage/ComponentsExample.svelte
  apps/docs/src/components/homepage/index.js
  apps/docs/src/includes/logo.md
  apps/docs/src/includes/sidebar.md
  apps/docs/src/pages/core/anchor.md
  apps/docs/src/pages/core/native-select.md
  apps/docs/src/pages/core/portal.md
  apps/docs/src/pages/core/tabs.md
  apps/docs/src/pages/index.md
  apps/docs/src/pages/theming/ssr.md
  apps/docs/src/theme.css
  apps/docs/src/theme/components/Layout.svelte
  apps/docs/src/theme/style.css
  apps/docs/src/theme/styles/layout.css
  apps/docs/svelte-docs.config.js
  packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.stories.svelte
  packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.ts
  packages/svelteui-core/src/components/Anchor/Anchor.styles.ts
  packages/svelteui-core/src/components/Button/Button.styles.ts
  packages/svelteui-core/src/components/Checkbox/Checkbox.styles.ts
  packages/svelteui-core/src/components/Checkbox/Checkbox.svelte
  packages/svelteui-core/src/components/Chip/Chip.svelte
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.styles.ts
  packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.svelte
  packages/svelteui-core/src/components/Grid/Col/Col.styles.ts
  packages/svelteui-core/src/components/IconRenderer/IconRenderer.svelte
  packages/svelteui-core/src/components/Image/BackgroundImage/BackgroundImage.styles.ts
  packages/svelteui-core/src/components/Image/Image.styles.ts
  packages/svelteui-core/src/components/Input/Input.styles.ts
  packages/svelteui-core/src/components/Input/Input.svelte
  packages/svelteui-core/src/components/Menu/Menu.svelte
  packages/svelteui-core/src/components/Modal/Modal.svelte
  packages/svelteui-core/src/components/NativeSelect/NativeSelect.stories.svelte
  packages/svelteui-core/src/components/NativeSelect/NativeSelect.svelte
  packages/svelteui-core/src/components/Popper/Popper.styles.ts
  packages/svelteui-core/src/components/Tabs/Tab/Tab.styles.ts
  packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte
  packages/svelteui-core/src/components/Tabs/Tabs.stories.svelte
  packages/svelteui-core/src/components/Text/Text.styles.ts
  packages/svelteui-core/src/components/TextInput/TextInput.styles.ts
  packages/svelteui-core/src/components/TextInput/TextInput.svelte
  packages/svelteui-core/src/components/Title/Title.stories.svelte
  packages/svelteui-core/src/components/Title/Title.svelte
  packages/svelteui-core/src/styles/index.ts
  packages/svelteui-core/src/styles/ssr.ts
  packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte
  packages/svelteui-core/src/styles/theme/SvelteUIProvider/index.ts
  packages/svelteui-core/src/styles/theme/SvelteUIProvider/svelteui.provider.ts
  packages/svelteui-core/src/styles/theme/types/DefaultProps.ts
  packages/svelteui-core/src/styles/theme/types/index.ts
  packages/svelteui-demos/src/components/Configurator/controls/SizeControl.svelte
  packages/svelteui-demos/src/demos/composables/actions/use-move/usage.svelte
  packages/svelteui-demos/src/demos/core/NativeSelect/NativeSelect.demo.objects.svelte
  packages/svelteui-demos/src/demos/core/NativeSelect/index.ts
Labels: enhancement

#287 [docs]: Made ComponentsExample mobile friendly
  apps/docs/src/components/homepage/ComponentsExample.svelte
  apps/docs/src/theme.css
Labels: documentation, enhancement

#289 [@svelteui/core]: remove aria-required from NativeSelect
  packages/svelteui-core/src/components/NativeSelect/NativeSelect.svelte
Labels: bug

#290 [docs]: remove outdated part about the config prop of SvelteUIProvider
  apps/docs/src/pages/theming/svelteui-provider.md
Labels: documentation
